### ISSUE TITLE
What's the environment you are using in the README file?

### ISSUE THREAD

**Issue by ZifanWu** [timoklein/redo#8]
Hi there,

I wonder which environment it is in the README file. I ran the official ReDO implementation using a replay ratio of 0.25 (target update freq=8000) and the default dormant threshold (0.025) on DemonAttack, and found the perf started to degrade after around 16M environment steps (64M frames) while the vanilla DQN agent didn't. Although there are only one seed for each setting, I think the trend is clear enough. Have you seen similar perf in your runs?

![redo_degrade](https://github.com/user-attachments/assets/29057648-9128-4e48-ac20-632108bef9b0)

**Comment by timoklein** [comment]
The environment is DemonAttack-v4 with the settings described in the README. I will clarify this!

> Have you seen similar perf in your runs?

No, I never ran the agent for 100M steps because it takes way too long. That's why I chose their setting with a high replay ratio: It exacerbates plasticity loss, allowing me to generate faster results.

**Comment by ZifanWu** [comment]
@timoklein Thank you for the reply and looking forward to your results!

**Comment by ZifanWu** [comment]
Oh, I forgot to mention: The env I was using was DemonAttackNoFrameskip-v0 (with sticky actions), which is the [default configuration](https://github.com/google/dopamine/blob/master/dopamine/discrete_domains/atari_lib.py#L96) in the official code.
